import "../globals.css";
import { Navbar } from "../_componets/navbar";
import Footer from "../_componets/footer";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <head>
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>
        </head>
        <body>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
