import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "../globals.css";
import { Navbar } from "../_componets/navbar";
import Footer from "../_componets/footer";
import SessionProviders from "../_componets/providers"

import { getServerSession } from "next-auth";
import { options } from "../api/auth/[...nextauth]/route";
import StoreProvider from "./StoreProvider";
import { Toaster } from "react-hot-toast";

const nunito = Nunito({
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      <head>
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>
      </head>
      <body className={nunito.className}>
      <SessionProviders session={session}>

        <StoreProvider>

          <Navbar/>
          <Toaster/>
          {children}
          <Footer/>
        </StoreProvider>

    
      </SessionProviders>
        </body>
    </html>
  );
}
