import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { options } from "../api/auth/[...nextauth]/route";

const nunito = Nunito({
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      <head>
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>
      </head>
      <body className={nunito.className}>
      <div className="container w-full h-screen text-[20px]">
      <div className="navigation">
            <ul>
                <li className="mt-3">
                    <a href="#">
                        <span className="icon">
                            <i className="bx bx-user-circle"></i>
                        </span>
                        <span className="title">User Profile</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span className="icon">
                            <i className="bx bx-user"></i>
                        </span>
                        <span className="title">Profile</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span className="icon">
                        <i className='bx bx-notepad'></i>                        
                        </span>
                        <span className="title">Transaction</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span className="icon">
                            <i className="bx bx-log-out"></i>
                        </span>
                        <span className="title">Sign Out</span>
                    </a>
                </li>
            </ul>
        </div>
          {children}
      </div>
        </body>
    </html>
  );
}